# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.25 AS builder

WORKDIR /workspace
COPY . .
ENV GOFLAGS="-mod=mod"
# RUN GO_FLAGS="" go build --installsuffix cgo
RUN make -f Makefile.prow build-local

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL io.k8s.display-name="kube-state-metrics" \
      io.k8s.description="This is a component that exposes metrics about Kubernetes objects." \
      summary="This is a component that exposes metrics about Kubernetes objects."

COPY --from=builder /workspace/kube-state-metrics  /usr/bin/kube-state-metrics
USER 1001
ENTRYPOINT ["/usr/bin/kube-state-metrics"]

LABEL com.redhat.component="kube-state-metrics" \
name="rhacm2/kube-state-metrics-rhel9" \
cpe="cpe:/a:redhat:acm:5.0::el9" \
summary="kube-state-metrics" \
io.openshift.expose-services="" \
io.openshift.tags="data,images" \
io.k8s.display-name="kube-state-metrics" \
maintainer="" \
description="kube-state-metrics" \
io.k8s.description="kube-state-metrics"
